print ("Daniel Lorenzo N. Manahan")
print ("Mataas na Bayan")
print ("November 11, 2003")
print ("Marinduque State College")
print ("BSI/T-2C")
print ("Basketball")
print ("Playing Online Games")
print ("Studying")
print ("Reading")
print ("Drawing")